id: I6B223920
legacy_id: P007844
ocr_import_info:
  bdrc_scan_id: W8LS16741
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T15:29:38'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:31:41.326012+00:00'
last_modified: 2022-09-04 11:32:23.785344
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS16741
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS16741
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཤེར་ཕྱིན་རྩ་བ་དང་འགྲེལ་པ།
  author: སྨན་རི་མཁན་ཆེན ༢༢་ཉི་མ་བསྟན་འཛིན།
statistics:
  ocr_word_mean_confidence_index: 0.9611782627564509
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I8LS16755:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS16755
      total_pages: 128
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I8LS16755.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9654578041522599
    legacy_id: v003
  I8LS16760:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS16760
      total_pages: 60
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I8LS16760.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9561267251782142
    legacy_id: v008
  I8LS16754:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS16754
      total_pages: 176
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I8LS16754.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.95734930184115
    legacy_id: v002
  I8LS16757:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS16757
      total_pages: 54
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I8LS16757.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9612551105846747
    legacy_id: v005
  I8LS16759:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS16759
      total_pages: 60
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I8LS16759.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9569476701254227
    legacy_id: v007
  I8LS16758:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS16758
      total_pages: 176
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I8LS16758.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.957938236637267
    legacy_id: v006
  I8LS16753:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS16753
      total_pages: 330
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS16753.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9667803859477083
    legacy_id: v001
  I8LS16756:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS16756
      total_pages: 180
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I8LS16756.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9578111508635062
    legacy_id: v004
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
