id: I6B223920
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T15:30:25+00:00'
last_modified: '2022-06-09T06:30:12.336078+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS16741
  title: ཤེར་ཕྱིན་རྩ་བ་དང་འགྲེལ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9848':
      image_group_id: I8LS16753
      title: Volume 1 of sher phyin rtsa ba dang 'grel pa/
      total_pages: 330
      order: 1
      base_file: 9848.txt
    0A13:
      image_group_id: I8LS16754
      title: Volume 2 of sher phyin rtsa ba dang 'grel pa/
      total_pages: 176
      order: 2
      base_file: 0A13.txt
    01DD:
      image_group_id: I8LS16755
      title: Volume 3 of sher phyin rtsa ba dang 'grel pa/
      total_pages: 128
      order: 3
      base_file: 01DD.txt
    B9EB:
      image_group_id: I8LS16756
      title: Volume 4 of sher phyin rtsa ba dang 'grel pa/
      total_pages: 180
      order: 4
      base_file: B9EB.txt
    F2D1:
      image_group_id: I8LS16757
      title: Volume 5 of sher phyin rtsa ba dang 'grel pa/
      total_pages: 54
      order: 5
      base_file: F2D1.txt
    64A5:
      image_group_id: I8LS16758
      title: Volume 6 of sher phyin rtsa ba dang 'grel pa/
      total_pages: 176
      order: 6
      base_file: 64A5.txt
    C6D6:
      image_group_id: I8LS16759
      title: Volume 7 of sher phyin rtsa ba dang 'grel pa/
      total_pages: 60
      order: 7
      base_file: C6D6.txt
    '6196':
      image_group_id: I8LS16760
      title: Volume 8 of sher phyin rtsa ba dang 'grel pa/
      total_pages: 60
      order: 8
      base_file: 6196.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
