id: P007844
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS16741
  title: ཤེར་ཕྱིན་རྩ་བ་དང་འགྲེལ་པ།
  author: ''
  volumes:
    9faa2f081f1e4bd48ef84ee0aa3e6ccb:
      image_group_id: I8LS16753
      title: ''
      volume_number: 1
      total_pages: 330
    390b4155fb5a436294aa38ca14a283ff:
      image_group_id: I8LS16754
      title: ''
      volume_number: 2
      total_pages: 176
    83bdb2d93a024d22b01687481c311dbe:
      image_group_id: I8LS16755
      title: ''
      volume_number: 3
      total_pages: 128
    ea34ce61a9c0402ba28db673f5021614:
      image_group_id: I8LS16756
      title: ''
      volume_number: 4
      total_pages: 180
    29ab6a0b759d4ae0b4cab31ac81caea1:
      image_group_id: I8LS16757
      title: ''
      volume_number: 5
      total_pages: 54
    4e51fba3ad424ba5be1b5eecdf39400b:
      image_group_id: I8LS16758
      title: ''
      volume_number: 6
      total_pages: 176
    ff6cfa0c08b14c2c8f1e90ca28890e05:
      image_group_id: I8LS16759
      title: ''
      volume_number: 7
      total_pages: 60
    b646a74e089241d592cb2dfa243e5a80:
      image_group_id: I8LS16760
      title: ''
      volume_number: 8
      total_pages: 60
ebook_metadata:
  title: ཤེར་ཕྱིན་རྩ་བ་དང་འགྲེལ་པ།
  author: ''
  sku: P007844
  cover: cover.jpg
  layers:
  - pagination
